version: "1"
rules:                      # Array of rules
  - base: master      # Required. Target branch
    upstream: kallistios:master    # Required. Must be in the same fork network.
    mergeMethod: merge  # Optional, one of [none, merge, squash, rebase, hardreset], Default: none.
    mergeUnstable: false    # Optional, merge pull request even when the mergeable_state is not clean. Default: false
    assignees:              # Optional
      - cepawiel
    reviewers:              # Optional
      - cepawiel
    conflictReviewers:      # Optional, on merge conflict assign a reviewer
      - cepawiel
label: ":arrow_heading_down: pull"  # Optional
conflictLabel: "merge-conflict"     # Optional, on merge conflict assign a custom label, Default: merge-conflict
