var searchData=
[
  ['ramdisk_0',['Ramdisk',['../group__vfs__ramdisk.html',1,'']]],
  ['random_1',['Random',['../group__vfs__rnd.html',1,'']]],
  ['re_20execution_20type_2',['Re-Execution Type',['../group__irq__reexec__codes.html',1,'']]],
  ['read_20modes_3',['CDDA Read Modes',['../group__cdda__read__modes.html',1,'']]],
  ['read_20sector_20mode_4',['Read Sector Mode',['../group__cd__read__sector__mode.html',1,'']]],
  ['read_20sector_20part_5',['Read Sector Part',['../group__cd__read__sector__part.html',1,'']]],
  ['read_20subcode_20type_6',['Read Subcode Type',['../group__cd__read__subcode__type.html',1,'']]],
  ['real_20time_20clock_7',['Real-Time Clock',['../group__rtc.html',1,'']]],
  ['receive_20status_20bits_8',['Receive Status Bits',['../group__bba__rbits.html',1,'']]],
  ['region_9',['P4 memory region',['../group__p4mem.html',1,'']]],
  ['region_20codes_10',['region codes',['../group__kbd__regions.html',1,'Region Codes'],['../group__hw__regions.html',1,'Region Codes']]],
  ['region_20settings_11',['Region Settings',['../group__fr__region.html',1,'']]],
  ['register_201_20rt_5fconfig1_20bits_12',['RTL8139C Config Register 1 (RT_CONFIG1) Bits',['../group__bba__config1bits.html',1,'']]],
  ['register_204_20rt_5fconfig4_20bits_13',['RTL8139C Config Register 4 (RT_CONFIG4) Bits',['../group__bba__config4bits.html',1,'']]],
  ['register_205_20rt_5fconfig5_20bits_14',['RTL8139C Config Register 5 (RT_CONFIG5) Bits',['../group__bba__config5bits.html',1,'']]],
  ['register_20rt_5frxconfig_20bits_15',['RTL8139C RX Config Register (RT_RXCONFIG) bits',['../group__bba__configrx.html',1,'']]],
  ['register_20values_16',['Register Values',['../group__maple__reg__values.html',1,'']]],
  ['registers_17',['registers',['../group__sh4__cr__regs.html',1,'Control Registers'],['../group__pvr__registers.html',1,'Registers'],['../group__asic__regs.html',1,'Registers'],['../group__maple__regs.html',1,'Registers'],['../group__bba__regs.html',1,'Registers']]],
  ['relocation_20types_18',['Relocation Types',['../group__elf__reltypes.html',1,'']]],
  ['rendering_19',['Direct Rendering',['../group__pvr__direct.html',1,'']]],
  ['reset_20type_20',['Reset Type',['../group__irq__reset__codes.html',1,'']]],
  ['reset_20values_21',['Reset Values',['../group__pvr__reset__vals.html',1,'']]],
  ['responses_22',['responses',['../group__cd__cmd__response.html',1,'Command Responses'],['../group__cd__cmd__status.html',1,'Command Status Responses'],['../group__maple__cmds.html',1,'Commands and Responses'],['../group__audio__aica__resp.html',1,'Responses']]],
  ['return_20values_23',['return values',['../group__bba__txrv.html',1,'Return Values'],['../group__maple__func__rvs.html',1,'Return Values'],['../group__net__drivers__returns.html',1,'TX Return Values']]],
  ['rom_24',['GD-ROM',['../group__gdrom.html',1,'']]],
  ['rom_20drive_25',['GD-ROM Drive',['../group__asic__events__gd.html',1,'']]],
  ['romdisk_26',['Romdisk',['../group__vfs__romdisk.html',1,'']]],
  ['rt_5fconfig1_20bits_27',['RTL8139C Config Register 1 (RT_CONFIG1) Bits',['../group__bba__config1bits.html',1,'']]],
  ['rt_5fconfig4_20bits_28',['RTL8139C Config Register 4 (RT_CONFIG4) Bits',['../group__bba__config4bits.html',1,'']]],
  ['rt_5fconfig5_20bits_29',['RTL8139C Config Register 5 (RT_CONFIG5) Bits',['../group__bba__config5bits.html',1,'']]],
  ['rt_5frxconfig_20bits_30',['RTL8139C RX Config Register (RT_RXCONFIG) bits',['../group__bba__configrx.html',1,'']]],
  ['rtl8139c_20config_20register_201_20rt_5fconfig1_20bits_31',['RTL8139C Config Register 1 (RT_CONFIG1) Bits',['../group__bba__config1bits.html',1,'']]],
  ['rtl8139c_20config_20register_204_20rt_5fconfig4_20bits_32',['RTL8139C Config Register 4 (RT_CONFIG4) Bits',['../group__bba__config4bits.html',1,'']]],
  ['rtl8139c_20config_20register_205_20rt_5fconfig5_20bits_33',['RTL8139C Config Register 5 (RT_CONFIG5) Bits',['../group__bba__config5bits.html',1,'']]],
  ['rtl8139c_20rx_20config_20register_20rt_5frxconfig_20bits_34',['RTL8139C RX Config Register (RT_RXCONFIG) bits',['../group__bba__configrx.html',1,'']]],
  ['rtl8139c_20transmit_20status_20bits_35',['RTL8139C Transmit Status Bits',['../group__bba__tbits.html',1,'']]],
  ['rumble_20pack_36',['Rumble Pack',['../group__peripherals__rumble.html',1,'']]],
  ['rx_37',['RX',['../group__bba__rx.html',1,'']]],
  ['rx_20config_20register_20rt_5frxconfig_20bits_38',['RTL8139C RX Config Register (RT_RXCONFIG) bits',['../group__bba__configrx.html',1,'']]]
];
