var searchData=
[
  ['c11_0',['C11',['../group__threading__c11.html',1,'']]],
  ['cables_1',['Cables',['../group__video__cables.html',1,'']]],
  ['cache_2',['Cache',['../group__system__cache.html',1,'']]],
  ['cacheability_20settings_3',['Cacheability Settings',['../group__mmu__cache__values.html',1,'']]],
  ['calculation_20modes_4',['Color Calculation Modes',['../group__pvr__txrenv__modes.html',1,'']]],
  ['calls_5',['System Calls',['../group__system__calls.html',1,'']]],
  ['camera_6',['Camera',['../group__peripherals__camera.html',1,'']]],
  ['capabilities_7',['capabilities',['../group__controller__caps.html',1,'Capabilities'],['../group__controller__query__caps.html',1,'Querying Capabilities']]],
  ['capability_20groups_8',['Capability Groups',['../group__controller__caps__groups.html',1,'']]],
  ['capacity_9',['Memory Capacity',['../group__hw__memsizes.html',1,'']]],
  ['card_10',['SD Card',['../group__vfs__sd.html',1,'']]],
  ['card_20function_11',['Memory Card Function',['../group__maple__memcard.html',1,'']]],
  ['cdda_20read_20modes_12',['CDDA Read Modes',['../group__cdda__read__modes.html',1,'']]],
  ['channel_20commands_13',['Channel Commands',['../group__audio__aica__ch__cmd.html',1,'']]],
  ['channel_20start_20values_14',['Channel Start Values',['../group__audio__aica__ch__start.html',1,'']]],
  ['channel_20update_20values_15',['Channel Update Values',['../group__audio__aica__ch__update.html',1,'']]],
  ['channels_16',['Channels',['../group__tmus.html',1,'']]],
  ['checks_17',['checks',['../group__version__runtime__check.html',1,'Checks'],['../group__version__comptime__check.html',1,'Checks']]],
  ['clamp_20mode_18',['U/V Clamp Mode',['../group__pvr__uv__clamp.html',1,'']]],
  ['clamping_20toggle_19',['Clamping Toggle',['../group__pvr__colclamp__switch.html',1,'']]],
  ['clipping_20modes_20',['Clipping Modes',['../group__pvr__clip__modes.html',1,'']]],
  ['clock_21',['Real-Time Clock',['../group__rtc.html',1,'']]],
  ['clock_20function_22',['Clock Function',['../group__maple__clock.html',1,'']]],
  ['codes_23',['codes',['../group__networking__icmpv6__unreachable.html',1,'Destination Unreachable Codes'],['../group__asic__events.html',1,'Event Codes'],['../group__irq__exception__codes.html',1,'Exception Codes'],['../group__maple__functions.html',1,'Function Codes'],['../group__networking__icmpv6__param__problem.html',1,'Parameter Problem Codes'],['../group__kbd__regions.html',1,'Region Codes'],['../group__hw__regions.html',1,'Region Codes'],['../group__cd__cmd__codes.html',1,'Syscall Command Codes'],['../group__networking__icmpv6__time__exceeded.html',1,'Time Exceeded Codes']]],
  ['color_24',['Color',['../group__pvr__ctx__color.html',1,'']]],
  ['color_20calculation_20modes_25',['Color Calculation Modes',['../group__pvr__txrenv__modes.html',1,'']]],
  ['command_20bits_26',['Command Bits',['../group__bba__cbits.html',1,'']]],
  ['command_20codes_27',['Syscall Command Codes',['../group__cd__cmd__codes.html',1,'']]],
  ['command_20responses_28',['Command Responses',['../group__cd__cmd__response.html',1,'']]],
  ['command_20status_20responses_29',['Command Status Responses',['../group__cd__cmd__status.html',1,'']]],
  ['command_20values_30',['TA Command Values',['../group__pvr__commands.html',1,'']]],
  ['commands_31',['commands',['../group__audio__aica__ch__cmd.html',1,'Channel Commands'],['../group__audio__aica__cmd.html',1,'Commands']]],
  ['commands_20and_20responses_32',['Commands and Responses',['../group__maple__cmds.html',1,'']]],
  ['comparison_20modes_33',['Comparison Modes',['../group__pvr__depth__modes.html',1,'']]],
  ['compilation_34',['Compilation',['../group__pvr__primitives__compilation.html',1,'']]],
  ['compile_20time_35',['Compile-Time',['../group__version__comptime.html',1,'']]],
  ['completion_20type_36',['completion type',['../group__irq__completion__codes.html',1,'Completion Type'],['../group__irq__interrupt__codes.html',1,'Interrupt (Completion Type)']]],
  ['config_20fields_37',['ISP Config Fields',['../group__fr__fields.html',1,'']]],
  ['config_20flags_38',['ISP Config Flags',['../group__fr__flags.html',1,'']]],
  ['config_20register_201_20rt_5fconfig1_20bits_39',['RTL8139C Config Register 1 (RT_CONFIG1) Bits',['../group__bba__config1bits.html',1,'']]],
  ['config_20register_204_20rt_5fconfig4_20bits_40',['RTL8139C Config Register 4 (RT_CONFIG4) Bits',['../group__bba__config4bits.html',1,'']]],
  ['config_20register_205_20rt_5fconfig5_20bits_41',['RTL8139C Config Register 5 (RT_CONFIG5) Bits',['../group__bba__config5bits.html',1,'']]],
  ['config_20register_20rt_5frxconfig_20bits_42',['RTL8139C RX Config Register (RT_RXCONFIG) bits',['../group__bba__configrx.html',1,'']]],
  ['configuration_43',['Configuration',['../group__netcfg.html',1,'']]],
  ['configuration_20flags_44',['Configuration Flags',['../group__ppp__flags.html',1,'']]],
  ['connection_20methods_45',['Connection Methods',['../group__fr__method.html',1,'']]],
  ['console_20types_46',['Console Types',['../group__hw__consoles.html',1,'']]],
  ['constants_47',['Addresses and Constants',['../group__pvr__addresses.html',1,'']]],
  ['constants_20and_20masks_48',['Constants and Masks',['../group__pvr__bitmasks.html',1,'']]],
  ['contexts_49',['Contexts',['../group__pvr__ctx.html',1,'']]],
  ['control_20bits_50',['MII Control Bits',['../group__bba__miicb.html',1,'']]],
  ['control_20registers_51',['Control Registers',['../group__sh4__cr__regs.html',1,'']]],
  ['controller_52',['controller',['../group__controller.html',1,'Controller'],['../group__ubc.html',1,'User Break Controller']]],
  ['counters_53',['Performance Counters',['../group__perf__counters.html',1,'']]],
  ['crc_54',['CRC',['../group__networking__crc.html',1,'']]],
  ['culling_20modes_55',['Culling Modes',['../group__pvr__cull__modes.html',1,'']]],
  ['current_56',['current',['../group__version__comptime__current.html',1,'Current'],['../group__version__runtime__current.html',1,'Current']]]
];
