var searchData=
[
  ['p4_20memory_20region_0',['P4 memory region',['../group__p4mem.html',1,'']]],
  ['pack_1',['Rumble Pack',['../group__peripherals__rumble.html',1,'']]],
  ['package_2',['Header Package',['../group__vmu__package.html',1,'']]],
  ['palettes_3',['Palettes',['../group__pvr__pal__mgmt.html',1,'']]],
  ['parameter_20problem_20codes_4',['Parameter Problem Codes',['../group__networking__icmpv6__param__problem.html',1,'']]],
  ['part_5',['Read Sector Part',['../group__cd__read__sector__part.html',1,'']]],
  ['partitions_6',['Partitions',['../group__fr__parts.html',1,'']]],
  ['paths_7',['Exit Paths',['../group__arch__retpaths.html',1,'']]],
  ['pc_8',['PC',['../group__vfs__dcload.html',1,'']]],
  ['performance_20counters_9',['Performance Counters',['../group__perf__counters.html',1,'']]],
  ['peripherals_10',['Peripherals',['../group__peripherals.html',1,'']]],
  ['phases_11',['Automaton Phases',['../group__ppp__phases.html',1,'']]],
  ['pixel_20modes_12',['Pixel Modes',['../group__video__modes__pixel.html',1,'']]],
  ['poll_20function_13',['Events for the poll() function',['../group__poll__events.html',1,'']]],
  ['polygon_20lists_14',['polygon lists',['../group__pvr__list__mgmt.html',1,'Polygon Lists'],['../group__pvr__lists.html',1,'Polygon Lists']]],
  ['port_15',['External Port',['../group__asic__events__ext.html',1,'']]],
  ['posix_16',['posix',['../group__system__posix.html',1,'POSIX'],['../group__vfs__posix.html',1,'POSIX'],['../group__threading__posix.html',1,'POSIX']]],
  ['powervr_17',['PowerVR',['../group__asic__events__pvr.html',1,'']]],
  ['powervr_20api_18',['PowerVR API',['../group__pvr.html',1,'']]],
  ['ppp_19',['PPP',['../group__networking__ppp.html',1,'']]],
  ['primary_20timer_20',['Primary Timer',['../group__tmu__primary.html',1,'']]],
  ['primitive_20bin_20sizes_21',['Primitive Bin Sizes',['../group__pvr__binsizes.html',1,'']]],
  ['primitives_22',['Primitives',['../group__pvr__primitives.html',1,'']]],
  ['problem_20codes_23',['Parameter Problem Codes',['../group__networking__icmpv6__param__problem.html',1,'']]],
  ['profiling_24',['Profiling',['../group__pvr__stats.html',1,'']]],
  ['protection_20settings_25',['Protection Settings',['../group__mmu__prot__values.html',1,'']]],
  ['protocol_20values_26',['Protocol Values',['../group__modem__protocols.html',1,'']]],
  ['pty_27',['PTY',['../group__vfs__pty.html',1,'']]]
];
